token:
  ttl: 3600000
  secret: tastetest-awdb-dev-secret-tastetest-awdb-dev-secret-tastetest

admin:
  username: admin
  email: admin@admin.com
  password: admin

vars:
  security:
    enable: true

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 443ee0f39ecc46
    password: 4734721f935fed

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}
