spring.application.name=TasteTest-AWDB

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=project
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false
spring.flyway.table=project_schema_version
spring.flyway.baseline-version=0
spring.flyway.schemas=project
spring.flyway.default-schema=project

# MVC
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Mail
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=443ee0f39ecc46
spring.mail.password=4734721f935fed
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Custom vars
vars.security.enable=true

# Server
server.port=8090

# Token
token.ttl=3600000
token.secret=https://www.youtube.com/watch?v=VBUMYOYJISc

# Admin
admin.username=admin
admin.email=admin@admin.com
admin.password=admin